### ISSUE TITLE
Fails on Apple M2 running standard Macos binary installation instruction

### ISSUE THREAD

**Issue by skol101** [osrf/homebrew-simulation#2790]
Please supply your brew configuration:

~~~
$ brew config

HOMEBREW_VERSION: 4.3.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: c763732882720f463e84a79ebc607ba54b81ea5d
Last commit: 34 hours ago
Core tap JSON: 10 Sep 13:58 UTC
Core cask tap JSON: 10 Sep 13:58 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.0NPnZSOkpW/org.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false

~~~

If you are reporting a build failure, please supply the build logs
with the `--verbose` flag:

After running brew install gz-sim8 --verbose --debug

~~~


[ 30%] Building CXX object src/CMakeFiles/gz-math7.dir/Vector3Stats.cc.o
cd /tmp/gz-math7-20240910-20768-1wsv82/gz-math-7.5.1/build/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DMAC_OS_X_VERSION=1080 -Dgz_math7_EXPORTS -I/tmp/gz-math7-20240910-20768-1wsv82/gz-math-7.5.1/include -I/tmp/gz-math7-20240910-20768-1wsv82/gz-math-7.5.1/build/include -I/tmp/gz-math7-20240910-20768-1wsv82/gz-math-7.5.1/build/core/include -isystem /opt/homebrew/include/gz/utils2 -stdlib=libc++ -O3 -DNDEBUG -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -fPIC -MD -MT src/CMakeFiles/gz-math7.dir/Vector3Stats.cc.o -MF CMakeFiles/gz-math7.dir/Vector3Stats.cc.o.d -o CMakeFiles/gz-math7.dir/Vector3Stats.cc.o -c /tmp/gz-math7-20240910-20768-1wsv82/gz-math-7.5.1/src/Vector3Stats.cc
[ 32%] Linking CXX shared library ../lib/libgz-math7.dylib
cd /tmp/gz-math7-20240910-20768-1wsv82/gz-math-7.5.1/build/src && /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E cmake_link_script CMakeFiles/gz-math7.dir/link.txt --verbose=1
/opt/homebrew/Library/Homebrew/shims/mac/super/clang++  -stdlib=libc++ -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -dynamiclib -Wl,-headerpad_max_install_names  -Wl,-undefined -Wl,dynamic_lookup -compatibility_version 7.0.0 -current_version 7.5.1 -o ../lib/libgz-math7.7.5.1.dylib -install_name @rpath/libgz-math7.7.dylib "CMakeFiles/gz-math7.dir/Angle.cc.o" "CMakeFiles/gz-math7.dir/AxisAlignedBox.cc.o" "CMakeFiles/gz-math7.dir/Color.cc.o" "CMakeFiles/gz-math7.dir/DiffDriveOdometry.cc.o" "CMakeFiles/gz-math7.dir/Frustum.cc.o" "CMakeFiles/gz-math7.dir/GaussMarkovProcess.cc.o" "CMakeFiles/gz-math7.dir/Helpers.cc.o" "CMakeFiles/gz-math7.dir/Kmeans.cc.o" "CMakeFiles/gz-math7.dir/Material.cc.o" "CMakeFiles/gz-math7.dir/MecanumDriveOdometry.cc.o" "CMakeFiles/gz-math7.dir/MovingWindowFilter.cc.o" "CMakeFiles/gz-math7.dir/PID.cc.o" "CMakeFiles/gz-math7.dir/Rand.cc.o" "CMakeFiles/gz-math7.dir/RollingMean.cc.o" "CMakeFiles/gz-math7.dir/RotationSpline.cc.o" "CMakeFiles/gz-math7.dir/SemanticVersion.cc.o" "CMakeFiles/gz-math7.dir/SignalStats.cc.o" "CMakeFiles/gz-math7.dir/SpeedLimiter.cc.o" "CMakeFiles/gz-math7.dir/SphericalCoordinates.cc.o" "CMakeFiles/gz-math7.dir/Spline.cc.o" "CMakeFiles/gz-math7.dir/SplinePrivate.cc.o" "CMakeFiles/gz-math7.dir/Stopwatch.cc.o" "CMakeFiles/gz-math7.dir/Temperature.cc.o" "CMakeFiles/gz-math7.dir/Vector3Stats.cc.o"  /opt/homebrew/lib/libgz-utils2.2.2.0.dylib

cd /tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/src && /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E cmake_symlink_library ../lib/libgz-math7.7.5.1.dylib ../lib/libgz-math7.7.dylib ../lib/libgz-math7.dylib
[ 32%] Built target gz-math7
/opt/homebrew/bin/doxygen /tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox
warning: Tag 'OUTPUT_TEXT_DIRECTION' at line 102 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'CLANG_ASSISTED_PARSING' at line 1073 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
warning: Tag 'CLANG_OPTIONS' at line 1081 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
warning: Tag 'CLANG_DATABASE_PATH' at line 1091 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
warning: Tag 'HTML_TIMESTAMP' at line 1238 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'FORMULA_TRANSPARENT' at line 1530 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'LATEX_SOURCE_CODE' at line 1838 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'LATEX_TIMESTAMP' at line 1854 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'RTF_SOURCE_CODE' at line 1928 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOCBOOK_PROGRAMLISTING' at line 2033 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'CLASS_DIAGRAMS' at line 2220 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOT_FONTNAME' at line 2262 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOT_FONTSIZE' at line 2269 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOT_TRANSPARENT' at line 2495 of file '/tmp/gz-math7-20240910-14205-6zrvcz/gz-math-7.5.1/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
[ 32%] Built target doc
make: *** [all] Error 2
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --version
/opt/homebrew/Library/Homebrew/ignorable.rb:27:in `block in raise'
BuildError: Failed executing: make install
1. raise
2. ignore
3. backtrace
4. irb
5. shell

...
Choose an action: 3
/opt/homebrew/Library/Homebrew/ignorable.rb:27:in `block in raise'
/opt/homebrew/Library/Homebrew/ignorable.rb:26:in `callcc'
/opt/homebrew/Library/Homebrew/ignorable.rb:26:in `raise'
/opt/homebrew/Library/Homebrew/formula.rb:3065:in `block in system'
/opt/homebrew/Library/Homebrew/formula.rb:3001:in `open'
/opt/homebrew/Library/Homebrew/formula.rb:3001:in `system'
/opt/homebrew/Library/Taps/osrf/homebrew-simulation/Formula/gz-math7.rb:38:in `block in install'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/fileutils.rb:240:in `chdir'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/fileutils.rb:240:in `cd'
/opt/homebrew/Library/Homebrew/formula.rb:3125:in `mkdir'
/opt/homebrew/Library/Taps/osrf/homebrew-simulation/Formula/gz-math7.rb:36:in `install'
/opt/homebrew/Library/Homebrew/debrew.rb:15:in `block in install'
/opt/homebrew/Library/Homebrew/debrew.rb:86:in `debrew'
/opt/homebrew/Library/Homebrew/debrew.rb:15:in `install'
/opt/homebrew/Library/Homebrew/build.rb:179:in `block (3 levels) in install'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:536:in `with_env'
/opt/homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
/opt/homebrew/Library/Homebrew/formula.rb:1583:in `block in brew'
/opt/homebrew/Library/Homebrew/formula.rb:3233:in `block (2 levels) in stage'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:536:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:3232:in `block in stage'
/opt/homebrew/Library/Homebrew/resource.rb:127:in `block (2 levels) in unpack'
/opt/homebrew/Library/Homebrew/download_strategy.rb:119:in `chdir'
/opt/homebrew/Library/Homebrew/download_strategy.rb:119:in `chdir'
/opt/homebrew/Library/Homebrew/download_strategy.rb:106:in `stage'
/opt/homebrew/Library/Homebrew/resource.rb:123:in `block in unpack'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `run'
/opt/homebrew/Library/Homebrew/resource.rb:229:in `stage_resource'
/opt/homebrew/Library/Homebrew/resource.rb:122:in `unpack'
/opt/homebrew/Library/Homebrew/resource.rb:96:in `stage'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/forwardable.rb:240:in `stage'
/opt/homebrew/Library/Homebrew/formula.rb:3210:in `stage'
/opt/homebrew/Library/Homebrew/formula.rb:1576:in `brew'
/opt/homebrew/Library/Homebrew/build.rb:133:in `block in install'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:536:in `with_env'
/opt/homebrew/Library/Homebrew/build.rb:125:in `install'
/opt/homebrew/Library/Homebrew/build.rb:232:in `<main>'

~~~
==> ENV
~~~
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j12
CMAKE_PREFIX_PATH: /opt/homebrew/opt/readline:/opt/homebrew/opt/sqlite:/opt/homebrew/opt/ruby:/opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /opt/homebrew/opt/python@3.12/Frameworks
PKG_CONFIG_PATH: /opt/homebrew/opt/gz-cmake3/lib/pkgconfig:/opt/homebrew/opt/gz-utils2/lib/pkgconfig:/opt/homebrew/opt/mpdecimal/lib/pkgconfig:/opt/homebrew/opt/openssl@3/lib/pkgconfig:/opt/homebrew/opt/readline/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/xz/lib/pkgconfig:/opt/homebrew/opt/python@3.12/lib/pkgconfig:/opt/homebrew/opt/libyaml/lib/pkgconfig:/opt/homebrew/opt/ruby/lib/pkgconfig:/opt/homebrew/opt/pybind11/share/pkgconfig:/opt/homebrew/opt/eigen/share/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/14
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk
ACLOCAL_PATH: /opt/homebrew/share/aclocal
PATH: /opt/homebrew/Library/Homebrew/shims/mac/super:/opt/homebrew/opt/cmake/bin:/opt/homebrew/opt/doxygen/bin:/opt/homebrew/opt/pybind11/bin:/opt/homebrew/opt/pkg-config/bin:/opt/homebrew/opt/openssl@3/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/xz/bin:/opt/homebrew/opt/python@3.12/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/opt/python@3.12/libexec/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: osrf/simulation/gz-math7 7.5.1 did not build
~~~
Same error when running brew install gazebo11 --verbose --debug

**Comment by skol101** [comment]
Manage to install gazebo11 by first running 
 brew install gz-math6
