### ISSUE TITLE
gz-utils2 fails to install on MacOS M1

### ISSUE THREAD

**Issue by mbampi** [osrf/homebrew-simulation#2926]
~~~
$ brew config

HOMEBREW_VERSION: 4.4.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6ea9df68df4868ce12ea7c51c85b57dce514f2e8
Last commit: 5 days ago
Branch: stable
Core tap JSON: 28 Dec 02:38 UTC
Core cask tap JSON: 28 Dec 02:38 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.mh3N4SK7Iq/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.2
Rosetta 2: false
~~~

When trying to run `brew install gz-harmonic`, it fails due to gz-utils2 failing to be installed.

Trying to run it by itself it gives (as expected) the same error. Here is the command with the debug flag.
~~~
$ brew install --debug gz-utils2

/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading gz-utils2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading gz-utils2
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::NullLoader): loading gz-utils2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading osrf/simulation/gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading osrf/simulation/gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading osrf/simulation/gz-cmake3
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/git --version
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading osrf/simulation/gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading osrf/simulation/gz-cmake3
==> Fetching osrf/simulation/gz-utils2
==> Downloading https://osrf-distributions.s3.amazonaws.com/gz-utils/releases/gz-utils-2.2.0.tar.bz2
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.13\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 -V
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.13\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://osrf-distributions.s3.amazonaws.com/gz-utils/releases/gz-utils-2.2.0.tar.bz2
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.13\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET --http1.1 https://osrf-distributions.s3.amazonaws.com/gz-utils/releases/gz-utils-2.2.0.tar.bz2
Already downloaded: /Users/matheusdbampi/Library/Caches/Homebrew/downloads/93f01565d732b5acea243f7ea212ea212571582a635a57c140f42bed8c258183--gz-utils-2.2.0.tar.bz2
==> Installing gz-utils2 from osrf/simulation
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading osrf/simulation/gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading osrf/simulation/gz-utils2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading osrf/simulation/gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading osrf/simulation/gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading gz-cmake3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /opt/homebrew/Library/Taps/osrf/homebrew-simulation/Formula/gz-utils2.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/git --version
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromNameLoader): loading gz-cmake3
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromNameLoader): loading gz-cmake3
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromTapLoader): loading osrf/simulation/gz-cmake3
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromTapLoader): loading osrf/simulation/gz-cmake3
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromAPILoader): loading cmake
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromAPILoader): loading pkgconf
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FromTapLoader): loading osrf/simulation/gz-cmake3
/usr/bin/env tar --extract --no-same-owner --file /Users/matheusdbampi/Library/Caches/Homebrew/downloads/93f01565d732b5acea243f7ea212ea212571582a635a57c140f42bed8c258183--gz-utils-2.2.0.tar.bz2 --directory /private/tmp/homebrew-unpack-20241227-20178-eczq43
==> cmake .. -DCMAKE_INSTALL_RPATH=@loader_path/../lib
==> make install
Last 15 lines from /Users/matheusdbampi/Library/Logs/Homebrew/gz-utils2/02.make:
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'RTF_SOURCE_CODE' at line 1928 of file '/tmp/gz-utils2-20241227-20178-nt93db/gz-utils-2.2.0/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOCBOOK_PROGRAMLISTING' at line 2033 of file '/tmp/gz-utils2-20241227-20178-nt93db/gz-utils-2.2.0/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'CLASS_DIAGRAMS' at line 2220 of file '/tmp/gz-utils2-20241227-20178-nt93db/gz-utils-2.2.0/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOT_FONTNAME' at line 2262 of file '/tmp/gz-utils2-20241227-20178-nt93db/gz-utils-2.2.0/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOT_FONTSIZE' at line 2269 of file '/tmp/gz-utils2-20241227-20178-nt93db/gz-utils-2.2.0/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOT_TRANSPARENT' at line 2495 of file '/tmp/gz-utils2-20241227-20178-nt93db/gz-utils-2.2.0/build/api.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
[ 66%] Built target doc
make: *** [all] Error 2
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --version
/opt/homebrew/Library/Homebrew/ignorable.rb:27:in `block in raise'
BuildError: Failed executing: make install
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 3
/opt/homebrew/Library/Homebrew/ignorable.rb:27:in `block in raise'
/opt/homebrew/Library/Homebrew/ignorable.rb:26:in `callcc'
/opt/homebrew/Library/Homebrew/ignorable.rb:26:in `raise'
/opt/homebrew/Library/Homebrew/formula.rb:3171:in `block in system'
/opt/homebrew/Library/Homebrew/formula.rb:3107:in `open'
/opt/homebrew/Library/Homebrew/formula.rb:3107:in `system'
/opt/homebrew/Library/Taps/osrf/homebrew-simulation/Formula/gz-utils2.rb:29:in `block in install'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/lib/ruby/3.3.0/fileutils.rb:240:in `chdir'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/lib/ruby/3.3.0/fileutils.rb:240:in `cd'
/opt/homebrew/Library/Homebrew/formula.rb:3239:in `mkdir'
/opt/homebrew/Library/Taps/osrf/homebrew-simulation/Formula/gz-utils2.rb:27:in `install'
/opt/homebrew/Library/Homebrew/debrew.rb:15:in `block in install'
/opt/homebrew/Library/Homebrew/debrew.rb:86:in `debrew'
/opt/homebrew/Library/Homebrew/debrew.rb:15:in `install'
/opt/homebrew/Library/Homebrew/build.rb:179:in `block (3 levels) in install'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:539:in `with_env'
/opt/homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
/opt/homebrew/Library/Homebrew/formula.rb:1623:in `block in brew'
/opt/homebrew/Library/Homebrew/formula.rb:3347:in `block (2 levels) in stage'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:539:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:3346:in `block in stage'
/opt/homebrew/Library/Homebrew/resource.rb:114:in `block (2 levels) in unpack'
/opt/homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
/opt/homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
/opt/homebrew/Library/Homebrew/download_strategy.rb:102:in `stage'
/opt/homebrew/Library/Homebrew/resource.rb:110:in `block in unpack'
/opt/homebrew/Library/Homebrew/mktemp.rb:90:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:90:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:90:in `run'
/opt/homebrew/Library/Homebrew/resource.rb:237:in `stage_resource'
/opt/homebrew/Library/Homebrew/resource.rb:109:in `unpack'
/opt/homebrew/Library/Homebrew/resource.rb:83:in `stage'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/lib/ruby/3.3.0/forwardable.rb:240:in `stage'
/opt/homebrew/Library/Homebrew/formula.rb:3324:in `stage'
/opt/homebrew/Library/Homebrew/formula.rb:1616:in `brew'
/opt/homebrew/Library/Homebrew/build.rb:133:in `block in install'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:539:in `with_env'
/opt/homebrew/Library/Homebrew/build.rb:125:in `install'
/opt/homebrew/Library/Homebrew/build.rb:232:in `<main>'
~~~

Any idea what the issue could be? And how to complete the installation on my system?
Thank you in advance!

**Comment by codevilot** [comment]
In my case, I installed Xcode and tried again, and it worked.

**Comment by mbampi** [comment]
The solution was just reinstalling Xcode, as suggested by Namheon Baek.

I did it by executing the following:

`sudo rm -rf /Library/Developer/CommandLineTools`

`xcode-select --install`

Working fine now. Thanks ✅
